// api/lib/gmail.js
// Reusable Gmail API helper.
// Handles OAuth token refresh automatically on every call.
// Imported by api/scout.js — reusable for any future agent needing Gmail access.
//
// Required Vercel env vars:
//   GMAIL_CLIENT_ID
//   GMAIL_CLIENT_SECRET
//   GMAIL_REFRESH_TOKEN  (generated by running: node scripts/gmail-auth.js)

const GMAIL_BASE = 'https://gmail.googleapis.com/gmail/v1/users/me'
const TOKEN_URL = 'https://oauth2.googleapis.com/token'

// ─────────────────────────────────────────
// getAccessToken
// Exchanges the stored refresh token for a short-lived access token.
// Access tokens expire after 1 hour — always refresh before each Scout run.
// ─────────────────────────────────────────
export async function getAccessToken() {
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: process.env.GMAIL_CLIENT_ID,
      client_secret: process.env.GMAIL_CLIENT_SECRET,
      refresh_token: process.env.GMAIL_REFRESH_TOKEN,
      grant_type: 'refresh_token'
    })
  })

  const data = await res.json()

  if (!data.access_token) {
    throw new Error(`[gmail] Token refresh failed: ${JSON.stringify(data)}`)
  }

  console.log('[gmail] Access token refreshed successfully')
  return data.access_token
}

// ─────────────────────────────────────────
// searchMessages
// Queries the Gmail inbox using standard Gmail search syntax.
// Returns array of { id, threadId } — fetch each with getMessage() for content.
// ─────────────────────────────────────────
export async function searchMessages(accessToken, query, maxResults = 50) {
  const params = new URLSearchParams({
    q: query,
    maxResults: String(maxResults)
  })

  const res = await fetch(`${GMAIL_BASE}/messages?${params}`, {
    headers: { Authorization: `Bearer ${accessToken}` }
  })

  const data = await res.json()

  if (data.error) {
    throw new Error(`[gmail] searchMessages failed: ${data.error.message}`)
  }

  const messages = data.messages || []
  console.log(`[gmail] searchMessages: found ${messages.length} messages for query "${query}"`)
  return messages
}

// ─────────────────────────────────────────
// getMessage
// Fetches full message content for a single Gmail message ID.
// Returns { id, threadId, from, fromEmail, subject, body, date, labelIds }
// Body is capped at 1000 chars — enough for Scout classification, not full email.
// ─────────────────────────────────────────
export async function getMessage(accessToken, messageId) {
  const res = await fetch(`${GMAIL_BASE}/messages/${messageId}?format=full`, {
    headers: { Authorization: `Bearer ${accessToken}` }
  })

  const msg = await res.json()

  if (msg.error) {
    throw new Error(`[gmail] getMessage failed for ${messageId}: ${msg.error.message}`)
  }

  // Extract headers into flat object
  const headers = {}
  ;(msg.payload?.headers || []).forEach(h => {
    headers[h.name.toLowerCase()] = h.value
  })

  // Parse sender: "Name <email@domain.com>" → name + email
  const fromRaw = headers.from || ''
  const fromEmail = (fromRaw.match(/<(.+?)>/) || [null, fromRaw])[1]?.toLowerCase().trim() || ''
  const fromName = fromRaw.replace(/<.+?>/, '').replace(/"/g, '').trim() || fromEmail

  // Decode body — Gmail uses base64url encoding
  const body = extractBody(msg.payload)

  return {
    id: msg.id,
    threadId: msg.threadId,
    from: fromName,
    fromEmail,
    subject: headers.subject || '',
    body: body.slice(0, 1000), // cap for Scout — we don't need full email text
    date: headers.date || '',
    labelIds: msg.labelIds || []
  }
}

// ─────────────────────────────────────────
// extractBody (internal — not exported)
// Recursively finds the text body in Gmail's nested payload structure.
// Prefers text/plain. Falls back to text/html with tags stripped.
// ─────────────────────────────────────────
function extractBody(payload) {
  if (!payload) return ''

  // Direct body data on the payload itself
  if (payload.body?.data) {
    return Buffer.from(payload.body.data, 'base64url').toString('utf-8')
  }

  // Multipart — search parts for text content
  if (payload.parts) {
    const plain = payload.parts.find(p => p.mimeType === 'text/plain')
    const html = payload.parts.find(p => p.mimeType === 'text/html')
    const target = plain || html

    if (target?.body?.data) {
      const decoded = Buffer.from(target.body.data, 'base64url').toString('utf-8')
      // Strip HTML tags if we fell back to text/html
      return target.mimeType === 'text/html'
        ? decoded.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()
        : decoded
    }

    // Recurse into nested parts (some emails have deeply nested structure)
    for (const part of payload.parts) {
      const result = extractBody(part)
      if (result) return result
    }
  }

  return ''
}
