-- Migration: extract expected_schedule schema
-- Extracted from live Supabase (ifhniwjdrsswgemmqddn) on 2026-04-17
-- Purpose: reproducible DB definition for wiggle-world HQ port
-- This migration is idempotent (IF NOT EXISTS everywhere)
--
-- Replica identity: DEFAULT (relreplident = 'd'). NOT in supabase_realtime
-- publication today.
--
-- NOTE: columns exist for monday–friday only. There are no saturday/sunday
-- columns today. Flagged in report in case that is intentional vs. a gap.

CREATE TABLE IF NOT EXISTS public.expected_schedule (
  id              integer     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  dog_name        text        NOT NULL,
  type            text        NOT NULL,
  monday          boolean     NULL DEFAULT false,
  tuesday         boolean     NULL DEFAULT false,
  wednesday       boolean     NULL DEFAULT false,
  thursday        boolean     NULL DEFAULT false,
  friday          boolean     NULL DEFAULT false,
  ask_when        boolean     NULL DEFAULT false,
  contact_method  text        NULL,
  contact_handle  text        NULL,
  notes           text        NULL,
  created_at      timestamptz NULL DEFAULT now()
);

-- IMPORTANT: the live table uses a serial sequence (expected_schedule_id_seq,
-- nextval(...) default) rather than IDENTITY. IDENTITY is the modern, more
-- portable equivalent and will produce the same effective behaviour when
-- re-created from scratch. If strict parity with the old sequence is needed,
-- replace the id line above with:
--   id  integer PRIMARY KEY DEFAULT nextval('expected_schedule_id_seq'::regclass),
-- and CREATE SEQUENCE expected_schedule_id_seq before this table.
-- Flagged in report.

-- RLS
ALTER TABLE public.expected_schedule ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anon read expected_schedule" ON public.expected_schedule;

CREATE POLICY "Allow anon read expected_schedule"
  ON public.expected_schedule
  FOR SELECT
  TO anon
  USING (true);
